In [1]:
from analysis import compute_bin_counts_per_timestep_single
import numpy as np
from utils import load_data

In [2]:
data = load_data('/Users/mariedelvalle/Documents/projects/RatInABox/neuro_rl/data/env_empty/seed_3/all_episodes_bins_seed_3')
print(data[0][0][0])
print(len(data[0][0][0]))

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.99972856 1.
 0.9002714  0.         0.         0.         0.         0.
 0.         0.        ]
20


In [3]:
bin_counts = compute_bin_counts_per_timestep_single(data, num_bins=20, threshold=0.1)
print(bin_counts)

[[ 0  0  0  0  0  0  0  0 13 16 17 19  4  3  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13 17 17 19  3  3  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13 17 17 19  3  3  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13 16 17 19  4  3  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13 16 17 19  4  3  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13 16 17 19  4  3  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13 16 17 19  4  3  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13 16 17 19  4  3  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13 16 17 19  4  3  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 14 16 17 19  4  3  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 14 16 17 19  4  3  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 14 16 17 19  4  3  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 14 16 18 19  4  2  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 14 16 18 19  4  2  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 14 16 18 20  4  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 14 16 18 20  4  2  0  0  0  0